# Configuración básica de RabbitMQ para Corvus

# Archivo de definiciones (precarga de colas, vhosts y usuarios)
load_definitions = /etc/rabbitmq/definitions.json

# Puertos
listeners.tcp.default = 5672
management.tcp.port = 15672

# Habilitar login de invitado (solo para entorno de desarrollo local)
loopback_users.guest = false
